### PR TITLE
Add ability to select result lists and set limit

### PR DESCRIPTION
**Pull request by opes**
You can now select which tab lists you want to see (i.e. history, bookmarks, and/or current tabs) as well as limit the results of those lists.

### CODE REVIEW

**Comment by opes** [comment]
@victal let me know if this is something you'd like to add. Also, would you mind if I did a little bit of refactoring/cleanup of the extension, as well as pretty up/style the options page?

**Comment by victal** [comment]
I think limiting the amount of results is a good idea, and adding an option to customize the result size limit seems fine to me, but I'm not sure if adding the list selections on the options page is the best way to do it.

Ideally, I think that limiting the results per list and improving the filter/removing duplicates (i found a couple bugs on that recently) on the add-on popup _should_ be enough for the user to find the intended page. 

If that's not possible not, I think maybe adding something to let the user filter the lists they want directly on the add-on page would be better. So far I thought of either toggling visibility of child items by clicking on a list header (and saving that state for future searches) or perhaps adding some keywords like +{list} or -{list} to let the users select the lists they want to see from the search input - that way the user wouldn't need to go to the options page every time they want to change that setting or if the lists change.

What do you think? In any case, I'll give a try at implementing one of those and if it doesn't work out too well I'll take a look at merging this again as an alternative.

**Comment by opes** [comment]
I like the idea of clicking the list headers to toggle it. The keywords could be really useful, provided they don't conflict with what the user is searching for.

I could easily rework this PR to move the list selection from the options to the popup itself if you'd like me to. The question I have is: how would the disabled/hidden state for the hidden lists be styled? Something like italicize the title when collapsed?

Additionally, if you don't have issues with the way I implemented the list selection/filtering - and it's just the options section that needs to be addressed - I could remove the options UI but leave the rest intact to build upon.

**Comment by opes** [comment]
@victal any thoughts on this?

**Comment by victal** [comment]
First of all, sorry this went unanswered for so long;

About the styling of the shown/hidden lists, I thought of adding an up/down chevron or arrow besides the link count (I think the idea came from some Bootstrap accordion example but I couldn't find the link) like so:
2018-06-04-210417_626x535_scrot
What do you think?

I ended up sketching out this idea on the `hide` branch in this repo to see how it'd work; 
Since the shown/hidden control happens in the popup instead of the options page (and only the results are shown/hidden instead of the whole list) the implementation ended up a bit different from this part of the PR. 

So, if you'd still like to rework the PR to add both features (hiding lists and limiting results) I think you could use that branch as a basis (at least the ideas, if not the code - the code is a bit ugly);

Otherwise, if you'd like to split the 'limit results' code into a new PR, I think that part looks fine and could be merged as is;

**Comment by opes** [comment]
Awesome, that looks great! I'm going to close this and break out the 'limit results' into a new PR as suggested; I think that's a good idea.

Afterwards, I'll take a look at the 'hide' branch and see what you've got so far.

**Pull request closed without merging**
