### PR TITLE
Add ability to customize keyboard shortcut

### PR DESCRIPTION
**Pull request by opes**
Also fixes an issue where the popup could be opened multiple times.

### CODE REVIEW

**Comment by opes** [comment]
~~Currently, the options input/UI for the shortcut is rudimentary, but it's at least a start. I didn't want this commit to get too unwieldy for a first PR. Eventually, I'd like to make it nicer/simpler than having to type in the modifier keys.~~

I went ahead and updated the UI. It wasn't too much extra. Note that it's currently only tested on Mac. Will check Windows when I have access to it.

**Comment by victal** [comment]
Thanks for the PR! 

I tested it locally on Windows and Linux and everything worked OK, as far as I could tell.

**Comment by opes** [comment]
Thanks for checking & merging, @victal! Any ideas on when we can see the changes uploaded to AMO?

**Comment by victal** [comment]
Sorry, I should have made that clear.

As `browser.commands.update` was added on Firefox 60 (and I misread somewhere that it would be released earlier this month) I was waiting for it to be released before uploading the new version of the extension.

Since FF 60 actually won't be released until next month I'll probably try to upload a new version this week or the next for those using Beta/Dev Edition/Nightly versions.

**Comment by opes** [comment]
No worries! Thanks for clarifying.

**Pull request merged**
