### PR TITLE
Add ability to set limit of results

### PR DESCRIPTION
**Pull request by opes**

### CODE REVIEW

**Comment by victal** [comment]
LGTM. Merging as discussed on #7.

**Comment by opes** [comment]
Hey @victal, any update on when we'll see this released to AMO?

**Comment by victal** [comment]
Actually, it should have been released right after the PR was merged. I'll check what happened and upload it (it'll be version 1.3.0, and should be up on AMO later today)

**Comment by opes** [comment]
Awesome, thank you!

**Pull request merged**
