### PR TITLE
Add toolbar icon & window size saving

### LINKED ISSUE #4: [SUGGESTION] Toolbar button & remember popup windows size
Wow, very nice. Opened tabs, history, bookmarks, all accessible/searchable from one place: this is a must.

I'm aware _quickcommands_ focuses on keyboard users, and alt+shift+R works fine. Yet for toolbar buttons aficionados (not sure I'd mention them if I wern't one of them!) a dedicated button would be welcomed.

The size of _quickcommands_' window is fixed by the extension, having it remember the user's resized preference would be welcomed as well. I think it starts at 600x500, which is small. I have to resize it each time I open it.

Thanks for this fast, smart extension.

### PR DESCRIPTION
**Pull request by opes**
Closes #4

### CODE REVIEW

**Comment by victal** [comment]
From what I tested, if the user closes the popup like a normal window, and not by pressing Esc or selecting a link, the window size won't be saved because `closeUp()` is not called;

Since `browser.windows.get(windowID)` won't work inside the onRemoved listener to get the actual window size, maybe adding a `unload` or `beforeunload` event listener on the popup to save the window size/state would work? 

If it works maybe the `onRemoved` listener could even be removed altogether.

**Comment by opes** [comment]
Thanks for checking it out, @victal. I'll get that fixed and pushed up shortly.

**Comment by opes** [comment]
Apologies for the delay, @victal. Updated with `beforeunload` and removed the `onRemoved` listener as requested. Let me know what you think.

**Comment by victal** [comment]
Thanks! I'll take a better look/merge/release later today, but from a quick look the changes seem ok.

**Pull request merged**
